Add new analytics events, introduce /vote endpoint
BloopAI/bloop pull request #671
Opened 2023-06-21 11:51 UTC by calyptobai

2023-06-22 07:58 UTC, anastasiya1155 commented
When is the identify call made? Preferably should be done after github login or on launch

2023-06-22 08:09 UTC, anastasiya1155 commented
For upvote route we need query_id, but FE doesn't know it. It is not present in answer stream

2023-06-22 08:14 UTC, anastasiya1155 requested changes

2023-06-22 08:14 UTC, anastasiya1155 commented on server/bleep/src/webserver/answer.rs
> +    Query(params): Query<Vote>,
we shouldn't use query params for POST requests, we should parse request body instead

2023-06-22 08:14 UTC, anastasiya1155 commented on server/bleep/src/webserver/answer.rs
> +}
also, should accept and track in analytics comment (for downvotes)

2023-06-28 15:38 UTC, calyptobai commented
@anastasiya1155 The identify call is now made on first login. Do we want it to also occur on a specific route, for users which are already logged in? It should now include the parameters you noted, though `user_id` *is* `user_name`.

Additionally:

> For upvote route we need query_id, but FE doesn't know it. It is not present in answer stream

The first message sent back from `/answer` has been changed from a thread ID string to an initialization object of the form:

```json
{
    "thread_id": "...",
    "query_id": "...",
}
```

> also, should accept (and track in analytics) the user comment left when downvoting the response

Now, `.../vote` replaces `positive: boolean` with a `feedback` parameter in the forms:

```json
{"type":"positive"}
```
```json
{"type":"negative","feedback":"..."}
```

2023-06-29 08:22 UTC, anastasiya1155 commented
I still don't see the 'identify' call in the analytics panel. Are you sure it is triggered in Tauri? As far as I remember login flow on the cloud and in Tauri differs.

2023-06-29 15:40 UTC, anastasiya1155 commented
I don't see any events for repo indexed/removed in the analytics console. fyi the FE uses `delete /repos/indexed` and `get /repos/sync` endpoints for managing repos

2023-06-29 16:48 UTC, calyptobai commented
> I still don't see the 'identify' call in the analytics panel. Are you sure it is triggered in Tauri? As far as I remember login flow on the cloud and in Tauri differs.

We should now track successful logins with `/remotes/github/login`.

> I don't see any events for repo indexed/removed in the analytics console. fyi the FE uses `delete /repos/indexed` and `get /repos/sync` endpoints for managing repos

Deletions are now tracked via `DELETE /repos/indexed`. Addition is tracked as part of `PUT /repos/indexed`.

2023-06-29 21:37 UTC, calyptobai commented
> We need to do some tweaks to identify call:
> 
> * device_id shouldn't have a trailing newline (previously was trimmed on the FE)
> * user_id should be the same as tracking_id from /config endpoint previously used by FE
> * github_username should be in traits

> I don't see events for repo adding/removing in the analytics console

These should now be addressed.

2023-06-30 06:55 UTC, anastasiya1155 approved these changes

2023-06-30 07:48 UTC, merged